data:
  - data/sigma_1.npz
  - data/sigma_2.npz


# contains configs only used during dev/testing stages
misc:

  # 1D proxy QCF parameters for generating ground truth events
  true_params: [0.72916667, 0.25, 0.6, 0.36458333, 0.25, 0.8]

  # number of true events to be generated
  n_true_events: [1000000, 1000000]