channels:
  - pytorch
  - nvidia
  - conda-forge
  - rapidsai
  - defaults

dependencies:
  - cupy=12.2.0
  - cuda-version=11.8
  - matplotlib=3.7.2
  - mpi=1.0=openmpi
  - mpi4py=3.1.4
  - numba=0.57.1
  - numpy=1.24.4
  - openmpi=4.1.5
  - pandas=2.0.3
  - pylibraft=23.8.0
  - python=3.10.12
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - pyyaml=6.0.1
  - scipy=1.11.2

  # for compiling
  - clang
  - clangxx
  - gxx
